const mongoose = require("mongoose");

const vehicleSchema = new mongoose.Schema(
  {
    sheetName: String,
    spreadsheetId: String,
    financialYear: String,
    sheetType: { type: String, default: "FML" },

    uniqueId: { type: String, unique: true, sparse: true },
    logisticsPartner: String,
    onroutePayment: String,
    onsiteReceivingstatus: String,
    challanNo: String,
    invoiceDate: String,
    invoiceNo: String,
    dateOfCollection: String,
    dispatchDate: String,
    actualDispatchDate: String,
    placeOfCollection: String,
    placeOfDelivery: String,
    otherLocationDelivery: String,
    overallKm: String,
    consigneeName: String,
    consigneeRegion: String,
    consigneeAddress: String,
    consignorName: String,
    consignorAddress: String,
    model: String,
    modelInfo: String,
    modelDetails: String,
    chassisNo: String,
    engineNo: String,
    tempRegNo: String,
    insuranceCompany: String,
    insuranceNo: String,
    fasTagNo: String,
    tokenNo: String,
    driverName: String,
    phoneNo: String,
    drivingLicenseNo: String,
    inchargeName: String,
    currentIncharge: String,
    date: String,
    time: String,
    vehicleLocation: String,
    vehicleStatus: String,
    deliveryDate: String,
    expecteddeliveryDate: String,
    dieselQuantity: String,
    dieselRate: String,
    dieselAmount: String,
    driverWages: String,
    returnFare: String,
    total: String,
    toll: String,
    border: String,
    totalBorder: String,
    fourLtrDiesel: String,
    gatePass: String,
    pettyCash: String,
    grandTotal: String,
    ptpAmount: String,
    ptpDiesel: String,
    secondPumpDiesel: String,
    otpProvider: [{ name: String, amount: String }],
    hpclCardDiesel: String,
    miscellaneousExpenses: String,
    remainingBalance: String,
    pdiStatus: String,
    pdiDate: String,
    taxPaymentReceipt: [{ name: String, amount: String }],
    billed: String,
    notes: String,
    deletedAt: { type: Date, default: null },
    petrolPumpUsage: [{
      pump: { type: mongoose.Schema.Types.ObjectId, ref: "PetrolPump" },
      pumpName: String,
      amount: String,
    }],
    sheetsRowIndex: { type: Number, default: null },
    pendingSheetSync: { type: Boolean, default: false },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    lastEditedBy: { type: String, default: null },  // stores username string
  },
  { timestamps: true }
);

vehicleSchema.index({ chassisNo: "text", engineNo: "text", driverName: "text", model: "text", uniqueId: "text", challanNo: "text" });

module.exports = mongoose.model("Vehicle", vehicleSchema);